import type { Book } from "./types";
import { analects } from "./books/analects";
import { artOfWar } from "./books/art-of-war";
import { bhagavadGita } from "./books/bhagavad-gita";
import { confessionsAugustine } from "./books/confessions-augustine";
import { discoursesEpictetus } from "./books/discourses-epictetus";
import { essaysMontaigne } from "./books/essays-montaigne";
import { historiesHerodotus } from "./books/histories-herodotus";
import { lettersFromAStoic } from "./books/letters-from-a-stoic";
import { meditations } from "./books/meditations";
import { nicomacheanEthics } from "./books/nicomachean-ethics";
import { peloponnesianWar } from "./books/peloponnesian-war";
import { republic } from "./books/republic";
import { taoTeChing } from "./books/tao-te-ching";
import { thePrince } from "./books/the-prince";
import { thinkingFastAndSlow } from "./books/thinking-fast-and-slow";

/**
 * The shelf. Generated by scripts/build-index.mjs — add a file to
 * content/books and run `npm run index`.
 */
export const books: Book[] = [
  analects,
  artOfWar,
  bhagavadGita,
  confessionsAugustine,
  discoursesEpictetus,
  essaysMontaigne,
  historiesHerodotus,
  lettersFromAStoic,
  meditations,
  nicomacheanEthics,
  peloponnesianWar,
  republic,
  taoTeChing,
  thePrince,
  thinkingFastAndSlow,
];

export const bySlug = (slug: string): Book | undefined =>
  books.find((b) => b.slug === slug);

export const categories = (): string[] =>
  Array.from(new Set(books.map((b) => b.category))).sort();

export type { Book };
