import type { Book } from "./types";
import { aRoomOfOnesOwn } from "./books/a-room-of-ones-own";
import { analects } from "./books/analects";
import { artOfWar } from "./books/art-of-war";
import { bhagavadGita } from "./books/bhagavad-gita";
import { communistManifesto } from "./books/communist-manifesto";
import { confessionsAugustine } from "./books/confessions-augustine";
import { democracyInAmerica } from "./books/democracy-in-america";
import { discoursesEpictetus } from "./books/discourses-epictetus";
import { essaysMontaigne } from "./books/essays-montaigne";
import { historiesHerodotus } from "./books/histories-herodotus";
import { interpretationOfDreams } from "./books/interpretation-of-dreams";
import { lettersFromAStoic } from "./books/letters-from-a-stoic";
import { leviathan } from "./books/leviathan";
import { meditations } from "./books/meditations";
import { nicomacheanEthics } from "./books/nicomachean-ethics";
import { onLiberty } from "./books/on-liberty";
import { onTheOriginOfSpecies } from "./books/on-the-origin-of-species";
import { peloponnesianWar } from "./books/peloponnesian-war";
import { republic } from "./books/republic";
import { soulsOfBlackFolk } from "./books/souls-of-black-folk";
import { taoTeChing } from "./books/tao-te-ching";
import { thePrince } from "./books/the-prince";
import { thinkingFastAndSlow } from "./books/thinking-fast-and-slow";
import { walden } from "./books/walden";
import { wealthOfNations } from "./books/wealth-of-nations";

/**
 * The shelf. Generated by scripts/build-index.mjs — add a file to
 * content/books and run `npm run index`.
 */
export const books: Book[] = [
  aRoomOfOnesOwn,
  analects,
  artOfWar,
  bhagavadGita,
  communistManifesto,
  confessionsAugustine,
  democracyInAmerica,
  discoursesEpictetus,
  essaysMontaigne,
  historiesHerodotus,
  interpretationOfDreams,
  lettersFromAStoic,
  leviathan,
  meditations,
  nicomacheanEthics,
  onLiberty,
  onTheOriginOfSpecies,
  peloponnesianWar,
  republic,
  soulsOfBlackFolk,
  taoTeChing,
  thePrince,
  thinkingFastAndSlow,
  walden,
  wealthOfNations,
];

export const bySlug = (slug: string): Book | undefined =>
  books.find((b) => b.slug === slug);

export const categories = (): string[] =>
  Array.from(new Set(books.map((b) => b.category))).sort();

export type { Book };
