/**
 * Regenerates content/index.ts from the files in content/books.
 * Each book file must export one const whose name is the camelCased slug.
 * Run with: npm run index
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const dir = "content/books";
const files = readdirSync(dir).filter((f) => f.endsWith(".ts")).sort();

const entries = files.map((f) => {
  const src = readFileSync(join(dir, f), "utf8");
  const m = src.match(/export const (\w+)\s*:\s*Book/);
  if (!m) throw new Error(`No exported Book const in ${f}`);
  return { name: m[1], mod: f.replace(/\.ts$/, "") };
});

const out = `import type { Book } from "./types";
${entries.map((e) => `import { ${e.name} } from "./books/${e.mod}";`).join("\n")}

/**
 * The shelf. Generated by scripts/build-index.mjs — add a file to
 * content/books and run \`npm run index\`.
 */
export const books: Book[] = [
${entries.map((e) => `  ${e.name},`).join("\n")}
];

export const bySlug = (slug: string): Book | undefined =>
  books.find((b) => b.slug === slug);

export const categories = (): string[] =>
  Array.from(new Set(books.map((b) => b.category))).sort();

export type { Book };
`;

writeFileSync("content/index.ts", out);
console.log(`index rebuilt: ${entries.length} books`);
